const express = require('express');
const registerAdmin = require('../controller/registerAdmin');
const registerUser = require('../controller/registerUser');
const accountDetail = require('../controller/accountDetail');
const logout = require('../controller/logout');
const loginAdmin = require('../controller/loginAdmin');
const getAllAdmins = require('../controller/getAllAdmins');
const getAllUsers = require('../controller/getAllUsers');
const getAdminById = require('../controller/getAdminById');
const updateAdminById = require('../controller/updateAdminById');
const updateUserById = require('../controller/updateUserById');
const getUserById = require('../controller/getUserById');
const addCategory = require('../controller/addCategory');
const getAllCategories = require('../controller/getAllCategories');
const updateCategoryById = require('../controller/updateCategoryById');
const getCategoryById = require('../controller/getCategoryById');
const blockAdminById = require('../controller/blockAdminById');
const blockUserById = require('../controller/blockUserById');
const deleteCategory = require('../controller/deleteCategory');
const visibleCategoryById = require('../controller/visibleCategoryById');
const getAllSubCategories = require('../controller/getAllSubCategory');
const deleteSubCategory = require('../controller/deleteSubCategory');
const addSubCategory = require('../controller/addSubCategory');
const updateSubCategoryById = require('../controller/updateSubCategoryById');
const getSubCategoryById = require('../controller/getSubCategoryById');
const addCardController = require('../controller/addCard');
const getAllCards = require('../controller/getAllCards');
const deleteCard = require('../controller/deleteCard');
const visibleCardById = require('../controller/visibleCardById');
const updateCardController = require('../controller/updateCardById');
const getCardById = require('../controller/getCardById');
const getSubCategoryByCategoryId = require('../controller/getSubCategoryByCategoryId');
const getAllCategoriesStatus1 = require('../controller/getAllCategoriesStatus1');

const router = express.Router();
router.get('/all-categories-status-1', getAllCategoriesStatus1);
router.get('/subcategories/:categoryId', getSubCategoryByCategoryId);
router.get('/card/:id', getCardById);
router.put('/card/:id', updateCardController.upload, updateCardController.updateCardById);
router.put('/card/:id/status', visibleCardById);
router.delete('/card/:id', deleteCard);
router.get('/all-cards', getAllCards);
router.post('/add-card', addCardController.upload, addCardController.addCard);
router.get('/subcategory/:id', getSubCategoryById);
router.put('/subcategory/:id', updateSubCategoryById);
router.post('/add-subcategory', addSubCategory);
router.delete('/subcategory/:id', deleteSubCategory);
router.get('/all-subcategories', getAllSubCategories);
router.put('/category/:id/status', visibleCategoryById);
router.delete('/category/:id', deleteCategory);
router.put('/user/:id/status', blockUserById);
router.put('/admin/:id/status', blockAdminById);
router.get('/all-categories', getAllCategories);
router.post('/add-category', addCategory);
router.put('/category/:id', updateCategoryById);
router.get('/category/:id', getCategoryById);
router.put('/user/:id', updateUserById);
router.get('/user/:id', getUserById);
router.put('/admin/:id', updateAdminById);
router.get('/admin/:id', getAdminById);
router.get('/all-users', getAllUsers);
router.get('/all-admins', getAllAdmins);
router.post('/register-admin', registerAdmin);
router.post('/register-user', registerUser);
router.get('/acc-details', accountDetail);
router.post('/logout', logout);
router.post('/login-admin', loginAdmin);
module.exports = router;